version: "3"

volumes:
  postgis13_data:
  pgadmin4_data:
services:
  db:
    image: postgis/postgis:13-3.1-alpine
    ports:
      - 5430:5432
    volumes:
      - postgis13_data:/var/lib/postgresql/data/
    env_file:
      - docker.env
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
